name: Open API Checks
on:
  - push
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm install -g @stoplight/spectral-cli
      - run: spectral lint rfq-api-v1.oas.yml
